name: MacOSx86_Tests

on: [push]

jobs:
  test:
    runs-on: macos-13
    strategy:
      matrix:
        python-version: [3.11]
    
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install UV
      run: pip install uv

    - name: Install
      run: ./install

    - name: Unit tests
      run: ./test
